### ISSUE TITLE
tpm2 access broker - no such version '2.2.1'

### ISSUE THREAD

**Issue by dhwalters423** [Infineon/amazon-greengrass-hsi-optiga-tpm#3]
Running through the following instructions: 
https://github.com/Infineon/amazon-greengrass-hsi-optiga-tpm/blob/master/README.md#install-tpm2-abrmd

Git shows the following error:
`error: pathspec '2.2.1' did not match any file(s) known to git.`

Suggest changing instructions to:
`git checkout 2.1.1`

**Comment by PeterHuewe** [comment]
Sorry for the typo, I'll update it.
Thanks for reporting
